### ISSUE TITLE
problems resizing

### ISSUE THREAD

**Issue by patapron** [michaschwab/easypz#10]
Hello

I have problems with my svg when resizing, 

```
no translate found matrix(0.07,0,0,0.07,312.48001419067384,199.01998580932616)
no scale found matrix(0.07,0,0,0.07,312.48001419067384,199.01998580932616)
```

**Comment by michaschwab** [comment]
Hi @patapron,
It's hard to help without any context. Can you provide a minimal example with this problem?
What are you resizing?
Best,
Micha

**Comment by michaschwab** [comment]
I'm closing this since there isn't enough information.
