### ISSUE TITLE
EasyPZ - Is there a way to update the transform object?

### ISSUE THREAD

**Issue by angieto** [michaschwab/easypz#11]
I have the code below for my onload function:

easyPZ = new EasyPZ(
          document.getElementById("image-panel"),
          function (transform) {
                        scale = transform.scale;
                        // newScale = tranform.scale * resizeScale
                        offset.x = transform.translateX;
                        offset.y = transform.translateY;
                        redrawAllCanvas(transform.scale, transform.translateX, transform.translateY);
                        // redrawAllCanvas(newScale, newTransform.translateX, newTransform.translateY);
           }
);

In cases where the canvas size bigger than the client screen size, I want to resize the image that fits to the screen size. So I calculate another scale called resizeScale. I want to implement the scale to the EasyPZ transform function. I wonder if there is a way that I could modify the transform object so it will return the offset.x and offset.y relative to the new scale (transform.scale*resizeScale)?

**Comment by michaschwab** [comment]
Hi and thanks for posting!
I see two paths here:

Option A: If you need help figuring out how to combine these two scales, as you described in your question, then I need a bit more information on how this resizeScale is used. Do you have a live example for me to look at? And what's the issue exactly? Why can you not use the translateX and Y that EasyPZ passes to the function and combine it with resizeScale somehow?

Option B: Often, when doing your own transformations, it's easiest to disentangle them from EasyPZ. For SVG elements, I'd recommend a separate top-level <g> element that handles the resizing to fit the window, and have EasyPZ operate on its child elements. For canvas, you can nest two transformation contexts within each other. This might be the easier approach. Here's an example of two nested transformations: https://jsfiddle.net/michaschwab/3dmfy84b/ - I still had to divide the translateX and Y by the resizeScale value, though.

Does that help?
Best,
Micha

**Comment by angieto** [comment]
Hi Micha,

Those are helpful options! The new scale itself (newScale = transform.scale * resizeScale) actually works. I store it as a global variable, update it whenever the transform function's called, and I use it for the redraw canvas function.

Thank you again for your response. I may implement option #2 in future!
Angie
