### ISSUE TITLE
Programmatically detach EasyPZ

### ISSUE THREAD

**Issue by stardisblue** [michaschwab/easypz#13]
Hello

I ran accross this problem when I was using easypz, and wanted to reset the zoom with a button.
Since the option did not exist, I tried to destroy and recreate an new EasyPZ object `new EasyPZ(samedom, ....)`, doing so N times creates an number of eventlisteners that I'm not able to remove (unless I recreate the DOM object and also loose whatever other eventlisteners were bound to it).

I did create a child class, ironically named DestroyableEasyPZ, but i think it should be doable to implement it in the original class.

https://observablehq.com/@stardisblue/hello-easypz

This could also serve other usecases where you want to enable/disable easypz while conserving the zoom and translate values.

**Comment by stardisblue** [comment]
I can also pull request this feature if you agree :)

**Comment by michaschwab** [comment]
Hi @stardisblue , thanks for your request!
For your use case of resetting zoom, I think there are better solutions than destroying EasyPZ.

But independent from the application, I think being able to detach EasyPZ could be useful. I would probably accept a pull request for that!

Best,
Micha

**Comment by michaschwab** [comment]
Thanks! Will resolve it in the pull request.
