### ISSUE TITLE
Remove Pan and Zoom Methods from Element

### ISSUE THREAD

**Issue by simonreger** [michaschwab/easypz#15]
Hello,

is it possible to remove the Zoom and Pan Methods from Canvas Element while the Script is running? Cause at some point of zooming and scrolling i want to draw something on that Canvas without the Methode of Paning. After drawing i want to add the Paning Method to the Canvase Element.

**Comment by michaschwab** [comment]
Hi!
Thanks for your request. I added this a little while ago but apparently forgot to respond here!
EasyPZ now has a "removeHostListeners" function that removes the listeners. Does that solve your problem?
Best,
Micha
