### ISSUE TITLE
1.1.11 is broken?

### ISSUE THREAD

**Issue by MyklClason** [michaschwab/easypz#18]
I noticed this on my site and I noticed it on the official easypz site as well in chrome and firefox. I'm getting:

```
Uncaught ReferenceError: exports is not defined
```

I ended up switching to a CDN for this via: `https://cdn.jsdelivr.net/npm/easypz@1.1.10/easypz.min.js` to ensure it wouldn't break again.

**Comment by michaschwab** [comment]
Oh no, I'm so sorry! I tried to add better integration with TypeScript but it broke the easy integration with JavaScript. I switched it back to how it was before. Thank you for letting me know, and I'll try to test my changes more in the future.
