### ISSUE TITLE
Going from touch to mouse

### ISSUE THREAD

**Issue by ezg** [michaschwab/easypz#2]
Great stuff! For the D3 examples on https://easypz.io/ I found that once I use touch to pan I can't use the mouse anymore. Basically going back and forth between touch and mouse to do panning doesn't work. 

Chrome (version 64.0.3282.167 (Official Build) (64-bit)) on a Surface Laptop.

**Comment by michaschwab** [comment]
Thanks! That makes sense, I didn't have hybrid devices with both touch and mouse in mind when designing EasyPZ. Will fix!

**Comment by michaschwab** [comment]
Thanks again @ezg for putting this on my radar! Sorry for addressing this late, but it should be fixed now! I borrowed a hybrid device to test it on and it seems to work now. Please let me know if there are any other issues.
