### ISSUE TITLE
Play lottie animation

### ISSUE THREAD

**Issue by Tectu** [michaschwab/easypz#22]
Is it possible to play a lottie animation inside the EasyPZ scene?

What I have working is an HTML5 canvas with EasyPZ and custom elements rendered within that and a lottie animation that is also rendered inside the same canvas. My question is: How can I get my lottie animation to play as part of the EasyPZ scene so when the user pans or zooms the animation also pans & zooms?

**Comment by michaschwab** [comment]
Hi Tectu!
Could you provide a minimal example so I can see what you are referring to? Thanks!
Micha

**Comment by Tectu** [comment]
Sorry for the long silence.
Unfortunately, the customer cancelled the project in the meantime so this is no longer a concern.
