### ISSUE TITLE
Bounding to element using Javascript does not work

### ISSUE THREAD

**Issue by AgainPsychoX** [michaschwab/easypz#23]
After hour of looking for simple SVG dragging library I found this, and now I feel so frustrated because it does not work properly...

https://jsfiddle.net/vdm2bL43/2/

**Comment by michaschwab** [comment]
Hi PsychoXIVI,
EasyPZ is actually working properly there - it's calling your callback function with translate properties, and letting you use them however you like. You're just not using it even though you're using the manual mode of easypz.
If you just want EasyPZ to automatically apply a transformation to your elements, I recommend using either the automatic mode that does not use JS, or basically do the same thing via JS: https://jsfiddle.net/michaschwab/ewnf3dsr/12/

If you want to set your own transformation on the elements manually, you can do it like this: https://jsfiddle.net/michaschwab/ewnf3dsr/15/
Best of luck!
